### ISSUE TITLE
Misalignment with small font sizes

### ISSUE THREAD

**Issue by ProbableTrain** [barvian/motion-number#2] opened 2024-08-21 09:39 UTC
Hi there, love this library!

I've noticed some misalignment between the characters at smaller font sizes, e.g. 14px. Here's a video and a code reproduction:

https://github.com/user-attachments/assets/17d200d0-2ef1-48f5-99b0-23e42375c8f1

Codepen: https://codepen.io/Keir-Lewis/pen/MWMVoEg

Sometimes it's bang-on perfect. Sometimes some characters will be noticeably vertically misaligned:
![Screenshot 2024-08-21 at 10 38 48](https://github.com/user-attachments/assets/66160b47-77ec-4190-b851-843950459440)

**Comment by ProbableTrain** [comment] 2024-08-21 13:42
Oh nice, that looks good! I missed the --mask-height var. Makes it look at lot better on non-high-dpi monitors too.

**Comment by barvian** [comment] 2024-08-21 15:28
Awesome! I'll look into improving this in the library by default (CSS round() would be perfect but it doesn't have the browser support yet) and/or make a note about it in the docs 👋

**Comment by barvian** [comment] 2024-08-21 16:42
Update: normal line-heights can cause this too; seems like everything needs to be rounded. I'll keep investigating and push a fix of some kind

**Comment by barvian** [comment] 2024-08-23 01:45
I think I've identified a fix; hoping to get to it this weekend 👍

**Comment by barvian** [comment] 2024-08-24 03:59
@ProbableTrain I just pushed version `0.1.7-next.0` with a potential fix for this. Would you mind testing against your initial pen to see if the alignment is better? It looks better for me locally, though I wasn't able to fully reproduce what you saw (side note: which browser were you using?)

**Comment by ProbableTrain** [comment] 2024-08-24 11:48
Thanks, I tried out 0.1.7-next.0 in the Codepen, and it's working perfectly!

**Comment by barvian** [comment] 2024-08-27 19:15
Update: I'm still looking into this. I'm not super confident that the change I pushed in 0.1.7-next.0 will work in every case, because it's the same one YouTube uses and I see the same problem sometimes with their numbers on Windows:

![youtube](https://github.com/user-attachments/assets/cf509dd5-3d13-4b45-ad66-850acccbcc8d)
![youtube2](https://github.com/user-attachments/assets/23ff6932-e7ae-4f40-a872-efa7a32fa434)

There's definitely a more "correct" way to fix this, but it's going to require a bit of experimentation and rework. I'll keep this issue updated!

**Comment by barvian** [comment] 2024-09-02 00:28
Anybody interested: I just pushed version `0.1.7-next.1` with a more proper fix for this that should handle all cases. It should be RC status but please let me know if you find issues!

**Closed** 2024-09-02 16:36 UTC
